[project]
name = "smart-contract-auditor"
authors = ["Your Name <your.email@example.com>"]
description = "AI-powered auditing tool for Clarity smart contracts"
telemetry = false
requirements = []

[contracts.auditor]
path = "contracts/auditor.clar"
depends_on = []

[contracts.example-contract]
path = "contracts/examples/example-contract.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
